### ISSUE TITLE
Docs need updating

### ISSUE THREAD

**Issue by JRCrawford** [prestaconcept/PrestaSitemapBundle#100]
The example code found here: https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-Usage-Event_Listener.md is not valid for Symfony3.x and greater ([see here](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#yaml))

Using the code: `arguments: [@router]` instead of `arguments: ["@router"]` will give the following error:
>  [Symfony\Component\Yaml\Exception\ParseException]
  The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 12 (near "arguments: [@router]").

**Comment by yann-eugone** [comment]
@JRCrawford can you make a PR for this ?
