### ISSUE TITLE
[1.5] undefined event->getGenerator

### ISSUE THREAD

**Issue by mysterty** [prestaconcept/PrestaSitemapBundle#115]
Since the update from 1.4 to 1.5, i have this error :
```
[Symfony\Component\Debug\Exception\UndefinedMethodException]                                                            
  Attempted to call an undefined method named "getGenerator" of class "Presta\SitemapBundle\Event\SitemapPopulateEvent".
```
But I don't see any change in the doc wich use that SitemapPopulateEvent : https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-Usage-Event_Listener.md

**Comment by yann-eugone** [comment]
Nice catch, yes the `getGenerator` method was removed in favor of `getUrlContainer`.
We will update the doc soon.

**Comment by yvalentin** [comment]
+1
Ok, thanks for this clarification !

**Comment by yann-eugone** [comment]
@yvalentin @mysterty #116 clear enough ?

**Comment by mysterty** [comment]
Good Job ;)

**Comment by yvalentin** [comment]
Yes thanks !
But the documentation isn't updated ;-)

**Comment by mysterty** [comment]
@yvalentin yes it is, but not merged yet into master ;)

**Comment by yann-eugone** [comment]
@yvalentin are you sure ? please see [changes](https://github.com/prestaconcept/PrestaSitemapBundle/pull/116/files)

**Comment by yvalentin** [comment]
Ok !! It's not yet merged ;-)
