### ISSUE TITLE
Unrecognized dumper_base_url config parameter in docs

### ISSUE THREAD

**Issue by bocharsky-bw** [prestaconcept/PrestaSitemapBundle#122]
https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/7-Dumper_command.md

**Comment by peschee** [comment]
Have the same error here with the latest version.

**Comment by bocharsky-bw** [comment]
Actually, this is a non-existent parameter in the current code base, same as `base-url` option for console dumper. It doesn't exist too. This docs page should be tweaked properly.

**Comment by yann-eugone** [comment]
@bocharsky-bw @peschee I opened a merge request ( #126 ) for this issue.
What do you think about it ?

**Comment by bocharsky-bw** [comment]
👍 It's a very convenient to have a `base-url` option for console command.

**Comment by peschee** [comment]
Nice, thank you.
