### ISSUE TITLE
Breaking change in minor version

### ISSUE THREAD

**Issue by geekdevs** [prestaconcept/PrestaSitemapBundle#124]
Hi,

I just wanted to mention that there's a breaking change when migrating `1.4.2` -> `1.5.0` (I got this: Call to undefined method Presta\\SitemapBundle\\Event\\SitemapPopulateEvent::getGenerator()). 
So this project is not following semantic versioning, it would probably make sense to set it to version `2.0` then as people normally do not expect to change anything in their code when updating minor version.

**Comment by yann-eugone** [comment]
Hi,
Yeah it's on me, I deleted the method instead of deprecating it, but I fixed it in a later pull request : #116 
It will be fixed in the next bugfix release.

**Comment by geekdevs** [comment]
thanks
