### ISSUE TITLE
Attempted to call an undefined method named "getGenerator"

### ISSUE THREAD

**Issue by netc00kie** [prestaconcept/PrestaSitemapBundle#125]
Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getGenerator" of class "Presta\SitemapBundle\Event\SitemapPopulateEvent"." at /var/www/website/src/BlogBundle/EventListener/SitemapListener.php line 42 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getGenerator\" of class \"Presta\\SitemapBundle\\Event\\SitemapPopulateEvent\". at /var/www/aramido.de/src/BlogBundle/EventListener/SitemapListener.php:42)"} []

Can you please advise?

**Comment by yann-eugone** [comment]
Yeah. The method has bee removed, a bit to quick. Sorry about that, the last release re-introduce the method but it triggers a deprecation notice.
