### ISSUE TITLE
SitemapListenerInterface is redurant

### ISSUE THREAD

**Issue by Koc** [prestaconcept/PrestaSitemapBundle#131]
There is no sense implement `SitemapListenerInterface` and create additional tag like `presta.sitemap.listener`. We could just subscribe for `SitemapPopulateEvent::ON_SITEMAP_POPULATE` and it enough. As additional feature - we can set priority in this case.

**Comment by yann-eugone** [comment]
I agree with this. But removing it as is will cause errors for everyone. I suggest that we deprecate it right now and remove it in the future major release.
What do you think ?

**Comment by Koc** [comment]
Of course, we should respect BC. Have you time to do this? If not I can create PR later.

**Comment by yann-eugone** [comment]
This is not big work : 
- deprecating the interface
- rewrite the doc

I can take a few minute this week to open a PR
