### ISSUE TITLE
IndexSitemap subdir issue

### ISSUE THREAD

**Issue by marcusthor** [prestaconcept/PrestaSitemapBundle#138]
Hello, 

I want to save the sitemap result to a subdir of the webroot ("http://localhost/sitemap/sitemap.xml") because the webroot isnt writeable for me:

`php bin/console presta:sitemaps:dump sitemap`

The index file and the sitemap.default.xml are both in this dir now and everything looks fine except the urls in the index sitemap.

> http://localhost/sitemap.default.xml

... but should be:

> http://localhost/sitemap/sitemap.default.xml

Is this possible to configure it this way?

Thank you
Marcus

**Comment by mhstudioos** [comment]
@thoerchen have you find a workaround for this configuration?

**Comment by thoerchen** [comment]
@mhstudioos i have no solution found yet. if you have an idea it would be nice if you can share

**Comment by mhstudioos** [comment]
@thoerchen the solution is already in the project: 

https://github.com/prestaconcept/PrestaSitemapBundle/commit/e6b7dbb464978afeb51bc3730084c422efcd9bee

but not yet in release v1.5

dump command:  
bin/console presta:sitemaps:dump {projectroot}/web/sitemap/ --base-url={host}/sitemap --gzip

**Comment by yann-eugone** [comment]
@marcusthor @mhstudioos https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v1.5.2 does it helps ?

**Comment by yann-eugone** [comment]
closing due to a lack of activity
if you still encounter this issue, please reopen
