### ISSUE TITLE
Sitemap format  ignored if use sections 

### ISSUE THREAD

**Issue by hmayaktigranyan** [prestaconcept/PrestaSitemapBundle#140]
If dumping sitemap `sectionA`

```
php app/console presta:sitemap:dump --gzip --section=sectionA
```

It adds `sitemap.sectionA.xml.gz` to `sitemap.xml`.
But if you then dump `sectionB` :

```
php app/console presta:sitemap:dump --gzip --section=sectionB
```

Then `sectionA` format changed to `sitemap.sectionA.xml` in `sitemap.xml` : the .gz extension was not kept

**Comment by yann-eugone** [comment]
Released in [`v2.1.0`](https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v2.1.0)
