### ISSUE TITLE
https links

### ISSUE THREAD

**Issue by rifats** [prestaconcept/PrestaSitemapBundle#141]
Hello! Thanks for bundle.
Is it enough to set `router.request_context.scheme: https` to get links with https:// in xml files?
It does not work for me either on the local dev server or on production.
I use CLI `php app/console presta:sitemap:dump` (S-2.8).

**Comment by ismithuk** [comment]
I'm getting this same issue, did you manage to resolve this @rifats

**Comment by rifats** [comment]
@ismithuk, no. If I'm not mistaken, http is hardcoded there.

**Comment by yann-eugone** [comment]
@rifats could you link me the part of code where `http` is hardcoded ? so I can investigate ?

**Comment by yann-eugone** [comment]
closing due to a lack of activity
also, we did not had a way to reproduce your issue

https://www.prestaconcept.net/sitemap.xml
https://www.prestaconcept.net/sitemap.blog.xml
