### ISSUE TITLE
Deprecation Notice with Symfony 3.3

### ISSUE THREAD

**Issue by elkangaroo** [prestaconcept/PrestaSitemapBundle#147]
After upgrading to Symfony 3.3, this bundle will trigger a deprecation notice:
> The Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher class is deprecated since version 3.3 and will be removed in 4.0. Use EventDispatcher with closure factories instead.

Trace:
> app/cache/dev/appDevDebugProjectContainer.php:2322: {▼
>         : $instance->addListenerService('presta_sitemap.populate', array(0 => 'presta_sitemap.eventlistener.route_annotation', 1 => 'populateSitemap'));

Orgin: AddSitemapListenersPass (call to `addListenerService`):  https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/DependencyInjection/Compiler/AddSitemapListenersPass.php#L47

**Comment by elkangaroo** [comment]
For me it looks like you could use the `RegisterListenersPass` instead, similar to the change in https://github.com/KnpLabs/KnpPaginatorBundle/pull/424

But as this bundle still supports Symfony 2.2, you need to pay attention that `RegisterListenersPass` moved from HttpKernel to EventDispatcher Component in 2.5! 

Maybe drop support for Symfony < 2.7 (have been EOLed long ago)?

**Comment by yann-eugone** [comment]
Hi, thank you for this spot.

If you read carefully the class you are talking about, you will notice that the entire feature has been deprecated : https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/DependencyInjection/Compiler/AddSitemapListenersPass.php#L39

You should not use the `presta.sitemap.listener` tag anymore.

Please have a look to the [documentation](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-Usage-Event_Listener.md)

**Comment by elkangaroo** [comment]
Thanks for the heads up, I didn't notice you deprecated this, since it was not part of the last tagged release (1.5.1).

Any plans for a new tagged release?

**Comment by yann-eugone** [comment]
Probably before september.

**Comment by yann-eugone** [comment]
I'm closing it, since the deprecation was already handled in #131
