### ISSUE TITLE
Incompatible with symfony flex

### ISSUE THREAD

**Issue by fracsi** [prestaconcept/PrestaSitemapBundle#153]
The package requires `symfony/symfony` but only uses a subset of symfony components.
The package cannot be installed when using [Symfony Flex](https://symfony.com/doc/current/setup/flex.html), because with flex you install symfony components individually, and they conflict with the `symfony/symfony` package.

**Comment by yann-eugone** [comment]
nice catch, someone's working on it : #154

**Comment by yann-eugone** [comment]
done in #153
closing
