### ISSUE TITLE
Documentation: sitemap live examples links are dead

### ISSUE THREAD

**Issue by chteuchteu** [prestaconcept/PrestaSitemapBundle#155]
The readme showcases two live example links in [Overview section](https://github.com/prestaconcept/PrestaSitemapBundle/tree/v1.5.2#overview) - both seems to be dead, with a `ERR_NAME_NOT_RESOLVED` error

We should probably remove these links, fix the underlying issue or replace them, shouldn't we?

**Comment by yann-eugone** [comment]
Nice catch, will have look to the while doc, opening a bigger issue for it.

**Comment by chteuchteu** [comment]
:+1: , thank you!
