### ISSUE TITLE
Rewrite the documentation

### ISSUE THREAD

**Issue by yann-eugone** [prestaconcept/PrestaSitemapBundle#156]
Things to fix in the documentation : 

## README.md

- [x] remove dead links as said in #155 (change sandbox to https://github.com/yann-eugone/presta-sitemap-test-project ?)
- [x] remove KnpBundles badge (useless)
- [x] remove google group link (not used anymore)
- [x] requirements should not be (only) a link to composer.json
- [x] remove lead dev information (not realistic)
- [x] remove bitlee badges (broken)

## 1-Installation.md

- [x] rewrite

## 2-Configuration.md

keep it like this

## 3-Usage-Quick_and_dirty.md

- [x] I don't think we should show dirty things, just remove this file

## 4-Usage-Routing_Config.md

- [x] Explain the expected result with such configuration (maybe the examples should be in the sandbox ?)

## 5-Usage-Event_Listener.md

- [x] rewrite
- [x] more examples
- [x] symfony 4 examples

## 6-Url_Decorator.md

- [x] rewrite
- [x] more examples
- [x] symfony 4 examples

## 7-Dumper_command.md

- [x] rewrite

## CONTRIBUTORS.md

- [x] remove this file (github page is enough)

**Comment by enekochan** [comment]
May be also change "Symfony2" to just "Symfony"? :)

**Comment by yann-eugone** [comment]
done in #158 
closing
