### ISSUE TITLE
Production server sitemap dump error 

### ISSUE THREAD

**Issue by janongush** [prestaconcept/PrestaSitemapBundle#161]
When I try to generate a dump of the sitemap using the command php bin/console presta:sitemaps:dump on my live server, I get the following error:

There are no commands defined in the "presta:sitemaps" namespace

Note that php bin/console presta:sitemaps:dump works on localhost but isn't working on the production server.
I'm using Symfony 3.3 and Presta 1.5.

**Comment by yann-eugone** [comment]
Hello, thank you for reporting this issue.

Are you sure that the bundle is enabled ?
Do you see the command in the list when you enter `bin/console` without the command name argument ?
Can you tell both precise versions of `Symfony` and `PrestaSitemapBundle` (ie 3.3.16 & 1.5.6) ?

**Comment by janongush** [comment]
Hey, I just checked AppKernel on production and noticed it is different from what I have on localhost. It is definitely a deployment issue. 

Thanks for the help.

**Comment by yann-eugone** [comment]
You're welcome.
