### ISSUE TITLE
sitemap example returns a 404 

### ISSUE THREAD

**Issue by coreygans** [prestaconcept/PrestaSitemapBundle#162]
In the README, there is a link to https://www.prestaconcept.net/sitemap.xml as an example of the bundle being used, but it returns a 404 error:

**Comment by coreygans** [comment]
Still getting a 404: 
![screen shot 2018-05-25 at 6 39 41 am](https://user-images.githubusercontent.com/5404391/40542631-7e5e29ec-5fe6-11e8-846c-9f3943b515a1.png)

**Comment by yann-eugone** [comment]
We've found the issue. It was on our side (deployment stuff). It should be fixed now.
