### ISSUE TITLE
Output with GoogleMultilangUrlDecorator

### ISSUE THREAD

**Issue by Tersoal** [prestaconcept/PrestaSitemapBundle#168]
Hi all.

I'm facing with an issue and can't see where is the problem.

When I generate the sitemap with normal links, I have no problem: I see the output as html page with the xml content.

![sitemap1](https://user-images.githubusercontent.com/6338830/44521360-12e35a00-a6d3-11e8-9ca9-0fcacc7a14c8.png)

But when I add translated routes with locales, the output is not html, but xml source itself that does not see properly on the browser, but if you inspect code I think it's OK.

![sitemap2](https://user-images.githubusercontent.com/6338830/44521358-12e35a00-a6d3-11e8-9107-56c1f2d78cac.png)

Can you help me to know if it's an issue, or I'm doing something wrong?

Cheers.

**Comment by yann-eugone** [comment]
Hi @Tersoal, thank you for using this bundle.

Maybe you can attach the XML source of your sitemap. Without it, we will not be able to provide help.

**Comment by Tersoal** [comment]
Here it is an example (is localhost).

`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"  xmlns:xhtml="http://www.w3.org/1999/xhtml"><url><loc>http://errata-compiler.rpgutilities.local/app_dev.php/</loc><lastmod>2018-08-23T13:56:46+02:00</lastmod><changefreq>monthly</changefreq><priority>1.0</priority><xhtml:link rel="alternate" hreflang="es" href="http://errata-compiler.rpgutilities.local/app_dev.php/" /><xhtml:link rel="alternate" hreflang="en" href="http://errata-compiler.rpgutilities.local/app_dev.php/en/" /></url><url><loc>http://errata-compiler.rpgutilities.local/app_dev.php/new-book</loc><lastmod>2018-08-23T13:56:46+02:00</lastmod><changefreq>monthly</changefreq><priority>0.8</priority><xhtml:link rel="alternate" hreflang="es" href="http://errata-compiler.rpgutilities.local/app_dev.php/new-book" /><xhtml:link rel="alternate" hreflang="en" href="http://errata-compiler.rpgutilities.local/app_dev.php/en/new-book" /></url><url><loc>http://errata-compiler.rpgutilities.local/app_dev.php/contact</loc><lastmod>2018-08-23T13:56:46+02:00</lastmod><changefreq>monthly</changefreq><priority>0.6</priority><xhtml:link rel="alternate" hreflang="es" href="http://errata-compiler.rpgutilities.local/app_dev.php/contact" /><xhtml:link rel="alternate" hreflang="en" href="http://errata-compiler.rpgutilities.local/app_dev.php/en/contact" /></url></urlset>
`

**Comment by yann-eugone** [comment]
Look like the problem is with the `xhtml` namespace, and it is not this bundle fault.
To me, the issue is on the browser side.

Besides, the generated XML is valid, and sitemaps are not for humans ;)

**Comment by Tersoal** [comment]
Thank you so much, I thought the same. I don't understand why Chrome does not render properly Google instructions about sitemap xml. Firefox neither.

Cheers.
