### ISSUE TITLE
Change routing format - symfony 4.1 deprecation warning

### ISSUE THREAD

**Issue by nakashu** [prestaconcept/PrestaSitemapBundle#169]
Symfony 4.1 made old _controller routing deprecated, it a little bit annoying when running tests.

>  1x: Referencing controllers with PrestaSitemapBundle:Sitemap:index is deprecated since Symfony 4.1, use "Presta\SitemapBundle\Controller\SitemapController::indexAction" instead.
> 1x: Referencing controllers with PrestaSitemapBundle:Sitemap:section is deprecated since Symfony 4.1, use "Presta\SitemapBundle\Controller\SitemapController::sectionAction" instead.

I'll happy to make an PR for this tiny change if it won't make any BC.

**Comment by yann-eugone** [comment]
Yes, nice catch. But yes, this will introduce BC.

Maybe it is just time to clean the bundle and think about next major version.

**Comment by ostrolucky** [comment]
AFAIK this was fixed in 2.0

**Comment by yann-eugone** [comment]
Since v2.0.1 we have a routing compatible with symfony >= 3.4
