### ISSUE TITLE
Remove or manage lastmod attribute for sitemaps in Sitemapindex list?

### ISSUE THREAD

**Issue by amurzaliev** [prestaconcept/PrestaSitemapBundle#171]
Is it possible to remove lastmod attribute from Sitemapindex list? If one of my sitemaps has not been updated, and then I execute dump command, the lastmod attribute for the sitemap will be updated anyway. It seems, there is no such feature, or I'm wrong.

**Comment by yann-eugone** [comment]
Hello,
You are right, there is no such feature. The lastmod attribute in the sitemap index is inherited from what is contained in the corresponding urlset.

Did you handled the lastmod for each of your URLs ?

**Comment by yann-eugone** [comment]
Closing due to a lack of activity.
Please feel free to reopen if you want to work on this.
