### ISSUE TITLE
Dump sitemap in a new directory

### ISSUE THREAD

**Issue by hscmargot** [prestaconcept/PrestaSitemapBundle#174]
Hello, 
I used with success the command line to dump sitemap. I dumped it in directory `public/sitemap`. I can see my sitemap via `localhost/sitemap/sitemap.xml`. I have two sections : `menu` and `content`, which are located in the same directory. But in the `sitemap.xml` I just see in location `localhost/sitemap.menu.xml` instead of `localhost/sitemap/sitemap.menu.xml`. 
I looked in documentation and I can't find how to do what I want. 
Is there a way to override the code of the bundle?

**Comment by yann-eugone** [comment]
Hello @hscmargot 
The problem you are encoutering is about "subdirectory".

I never tried to do something like this myself, so I cannot tell you if there is a workaround on this one.

If you want to override the code of the bundle, you can just change the class of the Dumper : https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/config/services.xml#L8
