### ISSUE TITLE
Wrong packagist setup? 

### ISSUE THREAD

**Issue by ostrolucky** [prestaconcept/PrestaSitemapBundle#183]
There is still no 1.6 on packagist. Please check if packagist integration is correct, recently they did some changes.

**Comment by ostrolucky** [comment]
cc @yann-eugone in case you don't subscribe to these issues

**Comment by yann-eugone** [comment]
I received it this morning but did not had time to have a look

**Comment by yann-eugone** [comment]
We will see at the next release, but it is fixed now (1.6.0 is available)
