### ISSUE TITLE
Make Default Target Directory Configurable

### ISSUE THREAD

**Issue by kiler129** [prestaconcept/PrestaSitemapBundle#187]
Currently the dump command has a hardcoded `public` directory as a default target:

https://github.com/prestaconcept/PrestaSitemapBundle/blob/903d142b83accf9965f708f26fe56314aa154d1a/Command/DumpSitemapsCommand.php#L74-L79

Maybe it will be possible to expose this as a setting? It generally doesn't change per-run and it's static on the application level.

**Comment by yann-eugone** [comment]
OK, the standard is hardcoded, but this is a default value.

I believe that your problem is that you are do not want to dump your sitemap to that directory, but you don't want to write that directory every time.

Maybe we can introduce a config entry to specify that default value.

What do you think ?

**Comment by kiler129** [comment]
@yann-eugone Exactly my point to get this value from the config with the default being the same as of now - I'm sorry if I wasn't clear :)

I want to improve DX in multiple applications where each one of them defines its sitemap destination (since for example `robots.txt` needs to know about it too, web server has a punch-hole for the folder with sitemap, WAF is not triggered for such requests etc) without sysadmin caring about configuring crontab to point to a directory.

**Comment by kiler129** [comment]
Thank you, it works amazingly :)

**Comment by yann-eugone** [comment]
Released in [1.7.0](https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v1.7.0)
