### ISSUE TITLE
Make Default Static Routes Section Configurable

### ISSUE THREAD

**Issue by kiler129** [prestaconcept/PrestaSitemapBundle#188]
Currently the static routes can either be dumped into default section or be configured on the route level to go to a different bucket. To improve DX I think we can add an option in the global configuration to specify where they actually land if no section was specified.

For example in our case we dump all static routes to "static" section (as SEO people requested  ¯\\\_(ツ)_/¯) and it's tedious to always put the section everywhere. This seems like a very simple change here :)

**Comment by yann-eugone** [comment]
Let me explain what I understand from this request.

The thing is to add a config variable, which will be used to define the default section of static routes.

Thinking about it, maybe having a set of rules to determine to which section belong which url could be helpful ?

I believe the job could be done here : https://github.com/prestaconcept/PrestaSitemapBundle/blob/112287ee66aad95f98ad34f85340e739b1ffd7d8/EventListener/RouteAnnotationEventListener.php#L92

**Comment by kiler129** [comment]
Works like a charm!

Thank you :)

**Comment by yann-eugone** [comment]
Released in [1.7.0](https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v1.7.0)
