### ISSUE TITLE
Discourage Usage Of Entity Manager

### ISSUE THREAD

**Issue by kiler129** [prestaconcept/PrestaSitemapBundle#189]
Very minor documentation glitch - https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/4-dynamic-routes-usage.md#eventlistener-class

In general you shouldn't encourage people to get repositories from the manager - they should always be injected. Injecting manager is kind of like getting the whole world ;)
I think we should add to the note below the code or modify the code to not inject manager (since there are no persists there and it's not needed).

**Comment by yann-eugone** [comment]
You're right.
But that example code was written for the sake of simplicity, and before Symfony 3.4, defining repository as service was kind of boring to explain.
