### ISSUE TITLE
Add cookbook entry how to generate different sitemaps for subdomains

### ISSUE THREAD

**Issue by Koc** [prestaconcept/PrestaSitemapBundle#19]
We have large amount of subdomains and need to generate different sitemaps for each one. Cuttently we have created one listener like this:

``` php
list($section, $subdomain) = explode('_', $event->getSection());
if ($section === 'multisite') {
  // generate urls for $subdomain
}
```

and bash

``` bash
php app/console p:s:d --section=multisite_domain1
php app/console p:s:d --section=multisite_domain2
# ... many lines
```

How it possible do it better?

**Comment by yann-eugone** [comment]
@Koc do you want me to work on this ?

**Comment by yann-eugone** [comment]
Closing due to a lack of activity.
Please feel free to reopen if you want to work on this.
