### ISSUE TITLE
Set Locale for populate ?

### ISSUE THREAD

**Issue by Noido** [prestaconcept/PrestaSitemapBundle#193]
Hi how i can setLocale for populate my sitemap  ?

I got error :   Call to a member function getLocale() on null so i need to set him but i dont know how i try this for have $request  in public function populate(SitemapPopulateEvent $event) but it 's not work

$request = $event->getRequest();
        $locale = $request->get('_locale');
        die($locale);

Thanks for your help

**Comment by yann-eugone** [comment]
Hello @Noido. Thank you for using this bundle.

I really want to help, but I'm not sure to understand what you are trying to do.
You need a locale to generate your sitemap urls, right ?
The event you are using has [no access](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Event/SitemapPopulateEvent.php) to the `Request` object. So calling `SitemapPopulateEvent::getRequest` will always fail.

I you really need the `Request` in your service, please follow [Symfony's official documentation](https://symfony.com/doc/current/service_container/request.html).

Hope I've understand your need and this answer will help you.

**Comment by Noido** [comment]
Hi @yann-eugone thanks all my site is like that mysite.com/en mysite.com/es mysite.com/de  it s why i need give the locale when i generate url but i don t see how i can do with your bundle.

For normal site i use localeRewriteListener with onKernelRequest for add /en /es etc with 

$request = $event->getRequest();

        $baseUrl = $request->getBaseUrl();
        $path = $request->getPathInfo();

        $locale = $request->get('_locale');
        if ($this->isLocaleSupported($request->get('_locale'))) {
            $locale = $this->supportedLocales[$request->get('_locale')];
        }

I dont  want necessary request in my service, just have your bundle work with my site 

Thanks for your help

**Comment by yann-eugone** [comment]
If you are having this issue with the usage of the dump command, it is a normal behavior : you have no request context, as you are in a cli.

If you are in a http context, it is really weird not to have a master request... But I'm not sure I can do something at this point.

Please try to explain what you are trying to do.

**Comment by yann-eugone** [comment]
Closing due to a lack of activity.
Please feel free to reopen if you want to work on this.
