### ISSUE TITLE
Unit Testing while using CLI Command?

### ISSUE THREAD

**Issue by stacoverf** [prestaconcept/PrestaSitemapBundle#195]
Hello,

I'm wondering what would be the best approach to perform a phpunit test for the EventSubscriber when it is ran by CLI Command to perform the dump since i'm seem to be unable to understand/find documentation regarding that specific scenario, is it possible to do at all?

As unit testing the bundle does not exists currently on the documentation, i also would like to request to be addressed if possible

**Comment by yann-eugone** [comment]
Hello @stacoverf ! Thank you for using this bundle.

I'm not sure to understand the kind of test you are trying to perform.

When you say "ran by CLI Command" did you mean that in your test you are using some kind of `exec` ?
If so, the only way to not onboard your event subscribers is to have register these services only in the prod environment.

If you rather want to test your listeners as a unit test, then there is nothing specific at all, you juste need to create an event object that you will pass to your listener under test.

IMO you should decide the kind of test you want to implement : unit or integration : 
* the unit test will be on your listeners only
* the integration test will use symfony command tester but will require actual services, directories...

**Comment by stacoverf** [comment]
I was looking at the situation from the wrong approach. You're right regarding i need to create an even object to pass to the listener. 

Hope this wasn't a waste of time question, thanks for the answer and the time!
