### ISSUE TITLE
Support for separate desktop and mobile URLs

### ISSUE THREAD

**Issue by antonsnowy** [prestaconcept/PrestaSitemapBundle#208]
> This two-way ("bidirectional") annotation helps Googlebot discover your content and helps our algorithms understand the relationship between your desktop and mobile pages and treat them accordingly. When you use different URLs to serve the same content in different formats, the annotation tells Google's algorithms that those two URLs have equivalent content and should be treated as one entity instead of two entities.
[https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls#annotation-in-sitemaps](https://developers.google.com/search/mobile-sites/mobile-seo/separate-urls#annotation-in-sitemaps)

I found [adding alternates](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-decorating-urls.md#adding-alternales) using the [multilang decorator](GoogleMultilangUrlDecorator.php). I changed format and remove $hreflang and $rel in new Google**Separate**UrlDecorator.php (copy of _GoogleMultilangUrlDecorator.php_)

```
protected function generateLinkXml($href)
{
    $xml = '<xhtml:link rel="alternate" media="only screen and (max-width: 640px)" href="' . Utils::encode($href) . '" />';
    return $xml;
}
```

 It works.

```
foreach ($goods as $good) {
    $loc = $this->urlGenerator->generate(
        'product_show',
        ['default' => $good->getId()],
        UrlGeneratorInterface::ABSOLUTE_URL
    );
    $url = new Sitemap\UrlConcrete($loc);
    $decoratedUrl = new Sitemap\GoogleSeparateUrlDecorator($url);
    $decoratedUrl->addLink(str_replace('www.example.com', 'm.example.com', $loc));
    $urls->addUrl($decoratedUrl, 'default');
}
```

**Comment by yann-eugone** [comment]
I'm not sure what value is added with this compared to the mobile implementation we have.
For that reason, I'm closing it.

If someone whant to contribute with this one, please feel free to reopen.
