### ISSUE TITLE
Duplicate sitemap urls when using dynamic routes and unable to remove lastmod from sitemap

### ISSUE THREAD

**Issue by blackdolphin65** [prestaconcept/PrestaSitemapBundle#209]
Hi,

When I am using dynamic routes PrestaSitemap builds the urls properly but the problem is that all urls are duplicated, this problem doesn't occur when using static routes. I also tried to remove last mod parameter in some dynamic routes removing any information from /config/packages/presta_sitemap.yaml but it keeps adding the lastmod

I am really stuck with this, as I think that the bundle is great and really helpful but I want to fix those little things.

P.S. I am using Symfony 4.2

Thanks for your time

**Comment by yann-eugone** [comment]
Hi ! Never encountered such problem.
Are you sure that your listener is not registered twice ?
The debug:container command may help.

**Comment by blackdolphin65** [comment]
Oh... I was blind and I did not notice that, you were right, the issue with duplicated routes was mine! Before I close the issue, do you know if it is possible remove lastmod parameter from dynamic routes? I tried to pass null lastmod to UrlConcrete constructor but it keeps getting the current date, so I modified UrlConcrete and it works but I wanted to know if it is possible do it without modify the class

Thanks!

**Comment by yann-eugone** [comment]
Since https://github.com/prestaconcept/PrestaSitemapBundle/pull/157 it should be, maybe you have a default value for lastmod in your config ?

**Comment by blackdolphin65** [comment]
I don't have any default value in my config, I only have the following configs: https://pastebin.com/HNAnhKvf and in the subscriber I pass directly null in the lastmod parameter

**Comment by yann-eugone** [comment]
In fact the default value of this parameter should be "now" if you did not set it : https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/DependencyInjection/Configuration.php#L71

**Comment by yann-eugone** [comment]
Closing as this seems to be already fixed.
Please feel free to reopen if you encounter this issue.
