### ISSUE TITLE
Managing translations

### ISSUE THREAD

**Issue by djimondev** [prestaconcept/PrestaSitemapBundle#211]
Hello, is there a mean to build sitemaps with alternate links foreach available locale ?

**Comment by yann-eugone** [comment]
Hello.

No, there is no such feature like this for now. I think that someone opened a [pull request](https://github.com/prestaconcept/PrestaSitemapBundle/pull/205) for something like this very recently.

**Comment by yann-eugone** [comment]
Pull request merged and released
