### ISSUE TITLE
 Type error: number_format() expects parameter 1 to be float, string given

### ISSUE THREAD

**Issue by fabianoroberto** [prestaconcept/PrestaSitemapBundle#212]
After changing sprintf into number_format there is this error

https://github.com/prestaconcept/PrestaSitemapBundle/commit/5727c2d623a26e7f41e2f8b6b78b49f48535bd51#diff-a9a2f17205bf2df761e9b71801b8456eR136

**Comment by yann-eugone** [comment]
It has been a while, sorry. Can you give us context on how you encountered this error.

Maybe paste the error stack trace & some code that show route config ?
