### ISSUE TITLE
Wrong 1.7.1 tag?

### ISSUE THREAD

**Issue by ostrolucky** [prestaconcept/PrestaSitemapBundle#217]
If you check https://github.com/prestaconcept/PrestaSitemapBundle/compare/v1.7.0...v1.7.1 it looks like it contains changes supposed to go into 2.x beta

**Comment by yann-eugone** [comment]
Just released https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v1.7.2

My bad on this
