### ISSUE TITLE
Sitemap dump directory absolute

### ISSUE THREAD

**Issue by yann-eugone** [prestaconcept/PrestaSitemapBundle#225]
At the moment, the configured directory where the sitemap is dumped is : 

- `web` for Symfony < 4.0
- `public` for Symfony >= 4.0

But this directory is not absolute.

Commands are usually triggered from the project root dir (where the composer.json is stored) so it makes no difference. But if you trigger your command from anywhere else, you may have dumped your sitemap files to an unwanted dir.

Should this bundle use absolute dir for default values ?

- `%kernel.root_dir%/../web` for Symfony < 4.0
- `%kernel.project_dir%/public` for Symfony >= 4.0

**Comment by ostrolucky** [comment]
I agree with this proposal, default paths should not rely where is the command running from

**Comment by yamilovs** [comment]
You cannot trust `Kernel::VERSION` constant to define public directory.   
Symfony 3.4 works perfectly with the flex system and `public` directory too.   

i think this parameter must be required to fill in configuration (without default value). And of course it mast be absolute.

**Comment by yann-eugone** [comment]
This is just a default value, we had to find a way to define it, and you can still change it if you want.

This is not easy to guess at that moment, **and it will be painful to require that every project configure it even if not using anything exotic**. So no, we won't go that way.

The `public` instead of `web` dir was introduced in symfony 4, then backported to 3.4 (for an easy update path I think).
