### ISSUE TITLE
Configured defaults (changefreq, priority...) are only added on non-decorated url

### ISSUE THREAD

**Issue by l-vo** [prestaconcept/PrestaSitemapBundle#228]
Hi :) 

Configured defaults are not added when urls are decorated: https://github.com/prestaconcept/PrestaSitemapBundle/blob/3ca9c8ac03b778674517086d378bdcafbd60a33d/Service/AbstractGenerator.php#L99

Is there any reason for that ? Or is it a bug ?

Thank you for your answer.
Regards.

**Comment by yann-eugone** [comment]
Hello !

I think it can be consider as a bug, but it may have a reason for that :
The final Url, if decorated, has no getter/setter for lastmod/changefreq/priority.

To handle this we could : 
Add an interface with these methods.
Add the interface to both `UrlConcrete` & `UrlDecorator`.
Implement these methods in `UrlDecorator` by chaining calls to `$decoratedUrl` if it implement the interface.

**Comment by yann-eugone** [comment]
I opened a Pull Request to fix this issue. Can you try it ?

```
composer require dev-decorated-urls-defaults@defaults
```

**Comment by yann-eugone** [comment]
Released in [`v2.1.0`](https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v2.1.0)
