### ISSUE TITLE
Is changelog abandoned?

### ISSUE THREAD

**Issue by Chrysweel** [prestaconcept/PrestaSitemapBundle#233]
I had version v1.6.0, I want to update and I see that there is version 2.0.1 but I can't find a record of what things or requirements have changed, because the changelog only has until version 1.5.0.

Do you plan to update the changelog? Can I currently see the changes in a specific file?

Thanks in advance!

**Comment by Chrysweel** [comment]
I see that 15 commits and 50 files changed.
https://github.com/prestaconcept/PrestaSitemapBundle/compare/v1.6.0...v2.0.1

**Comment by yann-eugone** [comment]
Hello !
We abandoned CHANGELOG in favor of release notes : https://github.com/prestaconcept/PrestaSitemapBundle/releases
You can see almost everything from that page.

The original CHANGELOG.md was kept for old versions.

**Comment by Chrysweel** [comment]
Ok thanks for your reply and velocity!
