### ISSUE TITLE
annotation routes are not added

### ISSUE THREAD

**Issue by nuryagdym** [prestaconcept/PrestaSitemapBundle#240]
Hi,
I installed it to my Symfony 4.4 project.
During installation only `config/bundles.php` changed, nothing else is added/edited under `config/` directory.
then I created `config/routes/presta_sitemap.yaml` and added following lines:

```
presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
```

as described in the documentation.
Then opened `/sitemap.xml` page which contains only this:

```
<sitemapindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">
```

All my static routes are defined in annotations, but nothing is listed in sitemap.xml.
I added `SitemapSubscriber` for dynamic routes and this one worked. However, routes in annotations are not listed.

**Comment by yann-eugone** [comment]
Hi there !
This is weird. This may be obvious but did your static routes has the `sitemap=true` option set ?
As shown is the doc : https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/3-static-routes-usage.md

**Comment by nuryagdym** [comment]
Sorry, I did not notice documentation about static routes. 
I thought setting
```
presta_sitemap:
   route_annotation_listener: true
```
is enough.
setting `options={"sitemap"=true}` worked
