### ISSUE TITLE
How to auto generate sitemap xml on request?

### ISSUE THREAD

**Issue by kirrg001** [prestaconcept/PrestaSitemapBundle#249]
Hi there!

The documentation says:

> Back to the installation instructions, you may have noticed that this bundle is declaring routes: /sitemap.xml and /sitemap.{section}.xml.
> That means that, whenever the sitemap is requested, it is built on demand (or build from cache if you configured an adapter for the bundle).

That is a little unclear to me. If I don't generate the sitemap manually, the sitemap is not built on demand for me.

I am using a sitemap listener to generate dynamic sitemap.xml. Plus I am using a few Annotations in some controllers.

This works great using `bin/console presta:sitemaps:dump`.

But for staging/production I want that the sitemap.*.xml get's generated on first request and is then cached until it needs to be regenerated.

Is there any more documentation for this?

config/presta_sitemap.yaml
```
presta_sitemap:
  route_annotation_listener: true
```

config/routes/presta_sitemap.yml
```
presta_sitemap:
  resource: '@PrestaSitemapBundle/Resources/config/routing.yml'
```

Thanks so much for the bundle <3

**Comment by kirrg001** [comment]
I could run a cronjob executing `bin/console presta:sitemaps:dump` once per day or so, but that's not ideal. I am used to generating the sitemap on the fly with other frameworks.

**Comment by yann-eugone** [comment]
Hello ! First of all, thank you for using the bundle, we are glad you like it ! 🙂

Let me clarify how this is working.

The bundle collect routes via an event listener, we have a built in listener that collect what we call "static routes". You can of course add routes on your own with a listener you created.
This is the case for both direct or dumped sitemap.

You can access the sitemap directly without dumping it (if you imported the bundle routes as described in [documentation](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/1-installation.md)).
Note that using this method the entire sitemap (all listeners are called) will be generated for every http call.
This result may be cached, using a doctrine cache adapter (also see [documentation](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/2-configuration.md#caching-the-sitemap)), but **caching and dumping are two different things**.

Please also note that there is a conversation (#241) about deprecating and removing cache support in next major version (you may not want to go that way).

If you do not want to schedule via crontab the generation of sitemap, you can have a look to the very recent [messenger integration](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/7-messenger-integration.md) that may help you triggering sitemap rebuild on demand.

**Comment by kirrg001** [comment]
Hey!

Thanks for quick & detailed reply!

> First of all, thank you for using the bundle, we are glad you like it ! 🙂

( :

> You can access the sitemap directly without dumping it (if you imported the bundle routes as described in documentation).

Alright I've just figured it out. My StaticController was too greedy. It matched any sitemap url, which prevents PrestaSitemapBundle to handle the sitemap request.

```
    /**
     * @Route("/{page} ", name="home", options={"sitemap" = true })
     */
    public function index(InertiaInterface $inertia, string $page = null) : Response
``` 

**Changed this to**

```
    /**
     * @Route("/{page} ", name="home", options={"sitemap" = true }, requirements={"page": "^(?!sitemap).+"}))
     */
    public function index(InertiaInterface $inertia, string $page = null) : Response
```

> Please also note that there is a conversation (#241) about deprecating and removing cache support in next major version (you may not want to go that way).

Yeah I saw that one :) I'll read through it now that it works.

Thanks so much!

**Comment by yann-eugone** [comment]
Yes, static routes are routes without required parameter : because the bundle cannot guess values by itself.
