### ISSUE TITLE
When dump failed tmp data are not cleaned

### ISSUE THREAD

**Issue by smelikmartin** [prestaconcept/PrestaSitemapBundle#258]
**PHP version(s) affected**: all

**Package version(s) affected**: 1.5.2 but will same on latest

**Description**  
When dumper dump file but will failed on privelages or something else then cleanup will not clean tmp folder. This cause disk space reduction issue.

**How to reproduce**  
throw exception on dump

**Possible Solution**  
catch exception on dump and clean tmp folder when dump failed

**Comment by yann-eugone** [comment]
@smelikmartin thank you for reporting this.

I just opened a PR that should fix this issue.

But 1.5.x is way to old to be patched.
As you reported it, and if the PR is accepted, I can cherry pick it on a 1.7.x version if you wish.

**Comment by smelikmartin** [comment]
@yann-eugone thx for fix. cherry pick it on a 1.7.x version would be nice ;-)

**Comment by yann-eugone** [comment]
@smelikmartin got some time to cherry pick this yesterday, tag was just created : https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v1.7.3 :)
