### ISSUE TITLE
Use specific base_url in dynamic sitemap

### ISSUE THREAD

**Issue by nkl-kst** [prestaconcept/PrestaSitemapBundle#263]
Hi,

we are using your bundle and it works great, but we are facing a (more or less) small problem: Our app runs behind a proxy, so the URLs generated in the sitemaps are based on the IP adress of the proxy. This happens because the app doesn't know that it's not the user who made the (proxied) request.

Is there any way to use a specific host for URLs in sitemaps, like we can do it with the `--base_url=http://example.com` parameter when dumping the sitemaps? I didn't find anything neither in the documentation nor in the code.

For now we dump the sitemap with the mentioned `--base-url` param. But if the dump is not available for some reason, the on-demand generated sitemap will have the URLs with IP adresses inside again.

Thanks for your help.

**Comment by yann-eugone** [comment]
Hi @nkl-kst !

Thank you for using this bundle :) 

Maybe the problem you are facing has something to do with request context : 
https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/2-configuration.md#configuring-your-application-base-url
https://symfony.com/blog/new-in-symfony-5-1-simpler-request-context

Or with proxy configuration : 
https://symfony.com/doc/current/deployment/proxies.html

Does it help ?

**Comment by nkl-kst** [comment]
Thanks for your response, Yann.

As far as I know, the content of your first two links only apply if we are using the dumper, where no request context is available. But we like to change the `base_url` when generating the sitemap on demand, where the request context and the `base_url` ist already available.

We will have a closer look at the proxy configuration options, as we did not know the posibility to define the http header where the client request informations are stored. Thanks for sharing this one!
