### ISSUE TITLE
Add default locale as hreflang when using alternate option

### ISSUE THREAD

**Issue by taylankasap** [prestaconcept/PrestaSitemapBundle#270]
This code should be removed:

https://github.com/prestaconcept/PrestaSitemapBundle/blob/63f54b809cc2f3cb82bf16cc866b9ea24421700b/EventListener/StaticRoutesAlternateEventListener.php#L69-L71

**Reason**

Both from [Google docs](https://developers.google.com/search/docs/advanced/crawling/localized-versions):

> Each <url> element must have a child element <xhtml:link rel="alternate" hreflang="supported_language-code"> that lists every alternate version of the page, including itself.

> Each language version must list itself as well as all other language versions.

I can open PR if that's okay.

**Comment by yann-eugone** [comment]
Hu @taylankasap :)

Thank you for reporting this enhancement.
Looks like you are right, regarding the doc you provided.

A PR would be nice. Will you be OK to add some tests too ?

**Comment by yann-eugone** [comment]
Released as of [v2.5.0](https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v2.5.0)
