### ISSUE TITLE
Make url generator available on `SitemapPopulateEvent`

### ISSUE THREAD

**Issue by kbond** [prestaconcept/PrestaSitemapBundle#286]
**Description**  
A very common use case for using this event is to use the url generator to generate URLs. I think it would be a nice quality of life improvement to make the url generator available on the event itself. If of interest, I can make a PR.

**Example**  
```php
$event->getUrlGenerator()->generate(...);
```

**Comment by yann-eugone** [comment]
I think most subscribers to this event has a direct dependency to the URL generator.

It could be a good DX idea to provide this service via the event. So yeah, I'd love a PR for that.

While you're working on this, please think about BC.
Everything must be optional if we want to include this in a 3.1.0.
We will be required to think about triggering deprecation too.
