### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by lahaxearnaud** [prestaconcept/PrestaSitemapBundle#289]
**Description**  

[SF 6.0](https://symfony.com/releases/6.0) is out since a few weeks. 
Did you planned to make the support ?

The changelog: https://github.com/symfony/symfony/blob/6.0/CHANGELOG-6.0.md

Locally on my project in SF 5.4 I did not have any deprecated in `var/log/dev.log` when I launch the command.

**Comment by yann-eugone** [comment]
There is no "plan", but we want support for recent versions of both PHP & Symfony.
So yes, this has to be done.

**Comment by yann-eugone** [comment]
Done in [`v3.2.0`](https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v3.2.0)

**Comment by lahaxearnaud** [comment]
Thanks @yann-eugone
