### ISSUE TITLE
Strange Behavior of merging - i think because of entity collision

### ISSUE THREAD

**Issue by gzhegow1991** [prestaconcept/PrestaSitemapBundle#293]
If you run `presta:sitemap:dump` without section - i think - author imagined as "regenerate all"
Usually on bigger projects it is high load task.
SEO operator (soldier/guy/troll/horse) wants from you "new sitemap in 15 minutes after content published" (yes, he never want to agree that things is not in sitemaps)
HA! Easy to say, hard to do.
OK, the script by default clears all the files and all urlsets and recreate new ones.

If you draw certain section - usually you want to extend current sitemap with new files. BUT we collide about "no-section" = regenerate all. Lets imagine we need update your TODAY sitemap every 15 minutes, and every day you need to regenerate ALL sitemaps. Once you recreate ALL sitemaps - you have to clear your TODAY list. But the file is still in robots.txt, so we cant delete it. BUT script does.

To get around i split my launch modes to "static", "today", "all". Static runs on "no-section" and creates sitemap `.static.xml`. Hey stop. Do you forget something? Yes, we need 2 sitemaps. `static.xml` and `static.google.xml`. Ok lets create 2 ones.

Next i'll run "today" script to create sitemap for blog news for today. Ok, same, 2 files. `.today.xml` and `.today.google.xml`.

I try what happens if i call "today" again... and i get confused. Sitemap index contains 6 items instead of 4. `.today` files presented twice. I dig deeper and found that the script creates URLset this way:
1. Create URLSET when any link added
2. Read presented URLSETs from existing index
**3. [ Collision here ] Add new URLSET only if name of generated file different from section you passed to command line.**

Actually i dont know how it should works, but you have to clear section that match between existing and new ones instead of passed via console. At least because each console call creates two files - `static` and `static.google`

Ok, maybe i should do it like "one file" = "one section" = "one passed section", then this script wont add new URLSETs cause of it match with console input. Entity collision that in console you usually expect "several sections"/"filter" but when you merge URLSETs you work with certain one and its existence.

**Comment by yann-eugone** [comment]
I'm sorry, I read this issue 4 times, and I'm not sure to understand what you are trying to do nor the problem you are encountering.
But yes, the idea behind sections is "one section = one file" (or many incremented files if you have to many content in it).

**Comment by gzhegow1991** [comment]
mybad. today will explain myself

**Comment by yann-eugone** [comment]
Closing, due to lack of activity
