### ISSUE TITLE
Main sitemap.xml and all other in differents folders

### ISSUE THREAD

**Issue by scion4581** [prestaconcept/PrestaSitemapBundle#294]
Hello! 
How could I separate the main sitemap.xml file and all others to place into different locations?
For example, public/sitemap.xml with links to others public/sitemap/sitemap.posts.xml, sitemap.articles.xml, and so on
The idea to have the one main sitemap file in the public directory and other in a subfolder of public directory
thanks

**Comment by norkunas** [comment]
Hi, you could decorate/extend the Dumper service to modify the `$target` directory. Just keep in mind that the `PrestaSitemapBundle_section` route path should also be aligned with your subfolder

**Comment by scion4581** [comment]
I didn't understand exactly, can't find $target directory parameter. 
As far as I know, the target path is just for dumping all files in same folder
The point was to place the sitemap index file separately from section sitemaps. 
public/
--- sitemap.xml ( with paths like `<loc>https://example.com/sitemap/sitemap.posts.xml</loc>`)
--- sitemap/sitemap.posts.xml (with paths like `<loc>https://example.com/news/some-news-url</loc>`)

**Comment by norkunas** [comment]
It could be something like:

```
final class Dumper implements DumperInterface
{
    public function __construct(private DumperInterface $decorated, private string $projectDir)
    {
    }

    public function dump(string $targetDir, string $host, string $section = null, array $options = [])
    {
        if ($section === null) $targetDir = $this->projectDir.'/public';
        if ($section !== null) $targetDir = $this->projectDir.'/public/sitemap';

        return $this->decorated->dump($targetDir, $host, $section, $options);
    }
}
```

**Comment by scion4581** [comment]
Unfortunately, this doesn't work - the root sitemap file and others appear in the same directory cause $targetDir same in the "dump" method for root sitemap.xml and sitemap.whatever.xml. 
I'll resolve this on a webserver level and paste it all in public/sitemap folder using the "dump_directory" option
It's a pity, it would be cool to have such an option out of the box
Anyway, a big thanks for the help!
