### ISSUE TITLE
Deprecation Warning as of Symfony 6.2

### ISSUE THREAD

**Issue by ok-ttc** [prestaconcept/PrestaSitemapBundle#307]
The following deprecation message is given:

`Since symfony/messenger 6.2: Implementing "Symfony\Component\Messenger\Handler\MessageHandlerInterface" is deprecated, use the "Symfony\Component\Messenger\Attribute\AsMessageHandler" attribute instead.`

This is surely not the most pressing, but will need adressing sooner or later.

**Comment by yann-eugone** [comment]
Released as of https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v3.3.1

**Comment by ok-ttc** [comment]
You are brilliant! :-)

**Comment by yann-eugone** [comment]
Thanks :)
To be fair, I just pressed few buttons to make it released ^^
All the fame must go to @franmomu & @norkunas for their work on https://github.com/prestaconcept/PrestaSitemapBundle/pull/303
