### ISSUE TITLE
Fill field lastmod on a per url basis ?

### ISSUE THREAD

**Issue by Yeye-Zfx** [prestaconcept/PrestaSitemapBundle#323]
Hi, 

Thanks for the bundle, it's great.
For dynamic pages, I haven't found how to  fill in the field lastmod for each url. Is it possible at all ?

**Comment by yann-eugone** [comment]
Hi, thanks for the kind words.

The `lastmod` is part of the `UrlConcrete` constructor, so when you create a new one in your listener, you can set it.

**Comment by Yeye-Zfx** [comment]
Thank you for your answer. 

I can't believe I missed that ! Indeed, the constructor of `UrlConcrete` has everything needed !
