### ISSUE TITLE
Drop Symfony 4.4, add Symfony 7

### ISSUE THREAD

**Issue by tacman** [prestaconcept/PrestaSitemapBundle#329]
Per the README

> This bundle is compatible with all Symfony versions since 2.3.0.

> However, like Symfony, we do not provide support for Symfony's version that reached EOL.

So the system requirements for symfony components should be ^5.4 || ^6.4 || ^7.0

**Comment by tacman** [comment]
Ah, I see there's a 4.0 branch already!

**Comment by yann-eugone** [comment]
Yes, it's on it's way for the release

**Comment by jonathanbull** [comment]
Any news on when 4.0 might be released? Greatly appreciate your work on this bundle.

**Comment by yann-eugone** [comment]
I just did https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v4.0.0
