### ISSUE TITLE
Namespace Issue in Sitemap

### ISSUE THREAD

**Issue by BriceFab** [prestaconcept/PrestaSitemapBundle#340]
### Problem Description

After updating the PrestaConcept bundle from version 3.3 to 4.1 in our project, we have encountered an issue as reported by Google's Search Console. The error message from Google indicates that there is a problem with namespaces: "The namespace is not correctly indicated in your index file or your sitemap."

Despite reviewing the sitemap output, the issue is not immediately apparent, as everything seems correct at first glance. This problem has arisen post-update, and we were not encountering this issue in the previous version of the bundle.

### Steps to Reproduce

1. Update the PrestaConcept bundle from version 3.3 to 4.1.
2. Generate the complex sitemap (with news, video, tags).
3. Submit the sitemap to Google's Search Console.

### Expected Behavior

The sitemap should be accepted by Google's Search Console without any namespace-related errors.

### Actual Behavior

Google's Search Console reports an error regarding the namespaces, suggesting they are not correctly indicated in the sitemap or index file.

### Additional Context

- This issue was not present in version 3.3 of the bundle.
- With our review of the sitemap's output we does not reveal any obvious misconfigurations or errors related to namespaces. 

I would greatly appreciate any guidance or recommendations on how to resolve this namespace issue.
Is there a known workaround or fix that could be applied to ensure compliance with Google's Search Console requirements?
I can open a PR if someone has more information about what's the problem reported from Google.

The sitemap URL is: https://www.fitmetrics.ch/sitemaps/sitemap.xml and https://www.fitmetrics.ch/sitemaps/sitemap.exercise.xml
![image](https://github.com/prestaconcept/PrestaSitemapBundle/assets/24533309/6c78e009-20b9-4ebb-a393-d89b2682b5c1)
![image](https://github.com/prestaconcept/PrestaSitemapBundle/assets/24533309/60219cd9-014c-420b-a5ca-c0e40a1a67ba)

### Environment

- PrestaConcept Bundle Version: 4.1
- PHP Version: PHP 8.2.16 
- Symfony Version: 6.4.3

Thank you for your time and assistance, and for your continued efforts in developing and maintaining the PrestaConcept bundle. Your work is greatly appreciated by the community.

**Comment by yann-eugone** [comment]
Hello,
So it was working with the bundle previous version?

I see you did your best at providing details, still it is not easy to understand what happen without the sitemap content.
Can you add to this issue:
- a sitemap that is valid
- the same sitemap but invalid

**Comment by roderikmutsaers** [comment]
Same error here. 

Problem seems to be the 'xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"' line in src/Sitemap/Sitemapindex.php
Google doesn't accept https over here. When changed to http the warning in Google Search Console is gone.

**Comment by BriceFab** [comment]
> Same error here.
> 
> Problem seems to be the 'xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"' line in src/Sitemap/Sitemapindex.php Google doesn't accept https over here. When changed to http the warning in Google Search Console is gone.

It was changed on the last release: https://github.com/prestaconcept/PrestaSitemapBundle/compare/v4.0.0...v4.1.0
I'll try to re-generate my sitemap with version v4.0.0 and sent it again to google search console. I keep you inform

**Comment by BriceFab** [comment]
> Same error here.
> 
> Problem seems to be the 'xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"' line in src/Sitemap/Sitemapindex.php Google doesn't accept https over here. When changed to http the warning in Google Search Console is gone.

I confirm the issue of https that is not allowed by Google:
![image](https://github.com/prestaconcept/PrestaSitemapBundle/assets/24533309/bca9eb68-4203-4645-8b0a-1a94415ab663)

By fixing the release to:
`"presta/sitemap-bundle": "4.0",`
It's work. https://github.com/prestaconcept/PrestaSitemapBundle/compare/v4.0.0...v4.1.0

cc @yann-eugone

**Comment by yann-eugone** [comment]
So it's all related to this https://github.com/prestaconcept/PrestaSitemapBundle/pull/337

But I don't understand why Google is struggling with https here
It seems that the http page is redirecting to the https page anyway

```
$ curl -sLD - http://www.sitemaps.org/schemas/sitemap/0.9

HTTP/1.1 301 Moved Permanently
Content-Length: 0
Date: Thu, 14 Mar 2024 13:38:03 GMT
Location: https://www.sitemaps.org/schemas/sitemap/0.9
```

**Comment by nediam** [comment]
Because its namespace identifier, not a URL ;) and namespace is with http://

**Comment by yann-eugone** [comment]
Here it is : https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v4.1.1
Sorry for not spotting that during the review
