### ISSUE TITLE
Support sitemap=false annotation

### ISSUE THREAD

**Issue by davidgorges** [prestaconcept/PrestaSitemapBundle#39]
It's currently not supported to set the sitemap option to "false". 

Presta/SitemapBundle/EventListener/RouteAnnotationEventListener.php line 97 {"exception":"[object] (InvalidArgumentException: the sitemap option must be \"true\" or an array of parameters at /home/www/wwwroot/sf2_widge_prod/shared/vendor/presta/sitemap-bundle/Presta/SitemapBundle/EventListener/RouteAnnotationEventListener.php:97

That's bad style. It shoudl accept the values true and false and the sitemap parameters as an additional parameter.

**Comment by yann-eugone** [comment]
This will be done in the next major release. See #92.
I'm closing this issue.
