### ISSUE TITLE
Allow changing default change frequency

### ISSUE THREAD

**Issue by fazy** [prestaconcept/PrestaSitemapBundle#61]
If most of the URLs on our site are changed weekly, it would be nice to be able to specify a config like this:

    presta_sitemap:
        default_changefreq: weekly

That way, we can cut down most of our routing.yml entry options from:

    options:
        sitemap: { priority: 0.5, changefreq: weekly }

to

    options:
        sitemap: { priority: 0.5 }

**Comment by yann-eugone** [comment]
This will be done in the next major release. See #92.
I'm closing this issue.
