### ISSUE TITLE
support for multilanguage

### ISSUE THREAD

**Issue by pculka** [prestaconcept/PrestaSitemapBundle#65]
Hi, this kinda doesn't work with jmstranslation bundle with nice translated URL's, see:

https://support.google.com/webmasters/answer/2620865?hl=en

as an example

**Comment by CharlyPoppins** [comment]
Hi, it has been a while,

so now is there a way to handle multi-language ?

**Comment by esion** [comment]
please see readme and #26

**Comment by CharlyPoppins** [comment]
Thanks found it too and it seems to work, but all links has to be done manually, anyway it seems to work, but xml is not displaying as "normal" xml files.
I'll show you a link when it'll be in "prod".

**Comment by CharlyPoppins** [comment]
Hi,
so here are my sitemaps :
http://materiaux-anciens-bidal.com/sitemap.xml well displayed (formatted in Chrome)
then my section fr is not well formatted
http://materiaux-anciens-bidal.com/sitemap.fr.xml
It seems to be correct, but why is it not displaying with the same format that sitemap.xml ?

**Comment by CharlyPoppins** [comment]
Hi, I'm working again on the SitemapListener, I still have the problem above.

sitemap.en.xml, sitemap.fr.xml are not well formatted

**Comment by yann-eugone** [comment]
@CharlyPoppins problem is not on server side, this is most about "this file is so big that the browser is disabling the XML preview"

**Comment by CharlyPoppins** [comment]
Maybe, but there is no **<?xml version="1.0" encoding="UTF-8"?>** in the first line. Is-it normal ?

**Comment by yann-eugone** [comment]
are you sure ? if i watch view-source:https://www.materiaux-anciens-bidal.com/sitemap.fr.xml i see the XML header

**Comment by CharlyPoppins** [comment]
Sorry, Safari wasn't displaying the XML header...
You're right I just try with a smaller file and it works well, thanks :)

**Comment by yann-eugone** [comment]
@pculka @schemar closing due to a lack of activity.

Also, I'm rewriting the broken links from #26 
- URL decoration documentation : [Resources/doc/6-Url_Decorator.md](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/6-Url_Decorator.md)
- URL multilang decorator class : [Sitemap/Url/GoogleMultilangUrlDecorator.php](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Sitemap/Url/GoogleMultilangUrlDecorator.php)
