### ISSUE TITLE
[STRUCTURE] Separate bundle and component for usage in other php mvc framework

### ISSUE THREAD

**Issue by jean-pasqualini** [prestaconcept/PrestaSitemapBundle#72]
[STRUCTURE] Separate bundle and component for usage in other php mvc framework

**Comment by alain-flaus** [comment]
Hello,

Yes you're right, that's a good idea/practice.
But for the moment all of our projects are using Symfony2, then it's not a priority for us to split it in a separate component.

**Comment by esion** [comment]
the bundle has been built with this constraint in mind. So it would easy to make a PR w/ `Sitemap\*` moved in an other lib.

_(hey @alain-flaus how r u?!)_

**Comment by yann-eugone** [comment]
No update on this, we tried something but without success, closing till somebody open a pull request
