### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by pulzarraider** [prestaconcept/PrestaSitemapBundle#75]
Can you, please, release new version of PrestaSitemapBundle (tag current master branch)?

The latest stable version is one year old.

**Comment by alain-flaus** [comment]
Hi,

You're right, but build has been failing for months.
It seems to be only checkstyle errors. I just made a PR to fix it (https://github.com/prestaconcept/PrestaSitemapBundle/pull/76).
The release is coming soon.

**Comment by alain-flaus** [comment]
Done.

https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v1.4.0

**Comment by pulzarraider** [comment]
Thank you @alain-flaus.
