### ISSUE TITLE
How to handle sections?

### ISSUE THREAD

**Issue by garak** [prestaconcept/PrestaSitemapBundle#80]
I hope I'm not asking a dumb question, but I couldn't find how to generate a sitemap for a specific section.
I'm calling URL /sitemap.foo.xml to get a "foo" section (I configurated my listener for it) but I get a 404.
I see that controller calls generator's `fetch` method, that calls `generate` method **without passing `$name`**.
I also tried to add `$name = null` to `generate()` and everything works. Is it a bug or am I doing it wrong?

**Comment by thanosp** [comment]
It looks like a bug to me as well. 
In order to get a section you need at least one url added via a listener with the section name as the 2nd parameter.
However the filtering by section seems impossible as all events have a NULL section. i.e. on every section the urls will be generated for all sections.

**Comment by yann-eugone** [comment]
@garak @thanosp not sure to understand this issue, could you explain it or open kind of demo projet to show me ?

**Comment by JPuigV** [comment]
@garak I had same problem as you, wanted to create multiple sections, but I was unable to get anything but a 404 from sitemap.{section}.xml. I started to fix the Generator class, passing the section to populate method, but then the root sitemap didn't display its children. After some tests, I realized that if I create a new SitemapListener for each section, all were successfully generated and displayed in root sitemap tree. So **for each section, use a new SitemapListener**. By the way, this bundle is good but lacks of some documentation in listener section. :)

**Comment by Koc** [comment]
As I understand - sections only useful when you dumping sitemaps using command. For controller it doesn't has sense.

**Comment by yann-eugone** [comment]
@garak @thanosp giving you a chance to explain it once more.

I opened a [demo project](https://github.com/yann-eugone/presta-sitemap-test-project) which I use to test the bundle as a developer.
If you can reproduce this issue with this, please feel free to re-open this issue with more information.
