### ISSUE TITLE
How to use dumper from controller?

### ISSUE THREAD

**Issue by lexxpavlov** [prestaconcept/PrestaSitemapBundle#82]
I want to dump a new item to sitemap after creating of new entity (e.g. page or product). But now Dumper service has very complex method dump(), which needs arguments $targetDir and $baseUrl.

I want more simple dump(), which will use default values:
```php
    $this->get('presta_sitemap.dumper')->dump(); // all sections
    $this->get('presta_sitemap.dumper')->dump('articles'); // section 'articles'

**Comment by yann-eugone** [comment]
This will be done in the next major release. See #92.
I'm closing this issue.
